# RESTful API
server:
  # server mode: release, debug, test;
  # Default: release
  mode: release
  # Enable server health check or notï¼Œif enabled, will install /healthz router;
  # Default: true
  healthz: true
  # Option values: secure, nocache, cors, dump, options.
  # Default: ""
  middlewares: secure,nocache,cors
  # Self ping check after server start;
  # Default: 3
  max-ping-count: 3

# HTTP
insecure:
  # Default: 127.0.0.1
  bind-address: 127.0.0.1
  # Default: 8080
  bind-port: 8080

# HTTPS
secure:
  # Default: 0.0.0.0
  bind-address: 0.0.0.0
  # If 0, means disable https;
  # Default: 8443
  bind-port: 8443
  tls:
    # x509 cert file, if null, will not enable https;
    # Default: ""
    cert-file: ./configs/cert/cert.pem
    # key file;
    # Default: ""
    key-file: ./configs/cert/key.pem

# MySQL
mysql:
  # Default: 127.0.0.1:3306
  host: 127.0.0.1:3306
  # Default: ""
  username: "root"
  # Default: ""
  password: "123456"
  # Default: ""
  database: "gobackend"
  # Default: 100
  max-idle-connections: 100
  # Default: 100
  max-open-connections: 100
  # Default: 10(s)
  max-connection-lifetime: 10
  # GORM log level: 1(silent), 2(error), 3(warn), 4(info)
  # Default: 1
  log-level: 4

log:
  # Logger Name;
  # Default: ""
  name: apiserver
  # debug, info, warn, error, dpanic, panic, fatal;
  # Default: info
  level: info
  # console, json;
  # Default: console
  format: console
  # Default: false
  disable-color: false
  # caller will print filename, funcname, line number;
  # Default: false
  disable-caller: false
  # stacktrace will print stack information above panic level;
  # Default: false
  disable-stacktrace: false
  # All log level messages will be writen to;
  # Default: stdout
  output-paths: stdout,./logs/gobackend-apiserver.log
  # Only log internal errors will be written to;
  # Default: stderr
  error-output-paths: stderr,./logs/gobackend-apiserver.error.log
  # Rotate log files or not;
  # Default: false
  enable-rotate: true
  # Maximum size in megabytes of the log file before it gets rotated,
  # if the value is 0, the log files will not be rotated.
  # Default: 100
  rotate-max-size: 100
  # Saved days, if 0, means no limit;
  # Default: 0
  rotate-max-age: 30
  # Saved count, if 0, means no limit;
  # Default: 0
  rotate-max-backups: 0
  # Use local time in log file name;
  # Default: true
  rotate-localtime: true
  # Gzip log files;
  # Default: false
  rotate-compress: false

feature:
  # If enable, it will add router: /metrics;
  # Default: true
  enable-metrics: true
  # <host>:<port>/debug/pprof/;
  # Default: true
  profiling: false
